#!/usr/bin/env python

from magical_ros2_conversion_tool.generators import update_generators
from magical_ros2_conversion_tool.manifest import update_manifest

from ros_introspection.util import get_packages

pkgs = get_packages()

for package in pkgs:
    print(package.name)

    update_manifest(package)
    update_generators(package)

    package.write()
