#!/usr/bin/python

from roscompile.package import get_packages

pkgs = get_packages()

for package in pkgs:
    print package.name
    package.manifest.add_packages([], [], ['roslint'])
    package.manifest.output()
    test_section = package.cmake.get_test_section(create_if_needed=True)
    test_section.check_dependencies(['roslint'], check_catkin_pkg=False)
    if len(package.get_python_source()) > 0:
        package.cmake.add_command_string('roslint_python()', True)

    if len(package.get_cpp_source()) > 0:
        package.cmake.add_command_string('roslint_cpp()', True)
    package.cmake.add_command_string('roslint_add_test()', True)
    package.cmake.output()
