#!/usr/bin/python

from roscompile.package import get_packages

pkgs = get_packages()

for package in pkgs:
    print package.name
    if not package.has_launch_folder():
        continue
    package.manifest.add_packages([], [], ['roslaunch'])
    package.manifest.output()
    test_section = package.cmake.get_test_section(create_if_needed=True)
    test_section.check_dependencies(['roslaunch'], check_catkin_pkg=False)
    package.cmake.add_command_string('roslaunch_add_file_check(launch)', True)
    package.cmake.output()
