#!/usr/bin/python

from __future__ import print_function

from roscompile.package import Package, get_packages, get_people_info
from roscompile.config import CFG

try:
    pkgs = get_packages()
except:
    print('roscompile only supports catkin format 1')
    exit()

if CFG.should('check_names'):
    people, replace = get_people_info(pkgs)

for package in pkgs:
    print(package.name)
    if CFG.should('check_names'):
        package.update_people(people, replace)

    if CFG.should('update_manifest'):
        package.update_manifest()
    elif CFG.should('check_names'):
        package.manifest.output()        

    if CFG.should('update_cmake'):
        package.update_cmake()

    if CFG.should('generate_setup_py'):
        package.generate_setup()

    if CFG.should('check_plugins'):
        package.check_plugins()

CFG.write()
