#!/usr/bin/python

import roslib; roslib.load_manifest('roscompile')       
from roscompile.package import Package, get_packages
from roscompile.config import CFG

pkgs = get_packages()

people = {}
for package in pkgs:
    for k,v in package.get_people().iteritems():
        people.update(v)

# TODO: Replace this with interactive version
people['David V. Lu!!'] = 'davidvlu@gmail.com'
replace = {'David!!': 'David V. Lu!!'}

for package in pkgs:
    print package.name
    package.update_people(people, replace)
    if CFG.should('update_manifest'):
        package.update_manifest()

    if CFG.should('update_cmake'):
        package.update_cmake()

    if CFG.should('generate_setup_py'):
        package.generate_setup()

    if CFG.should('check_plugins'):
        package.check_plugins()

CFG.write()
